A<-matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,ncol=3,byrow=TRUE)
B<-matrix(c(9,8,7,6,5,4,3,2,1),nrow=3,ncol=3,byrow=TRUE)
result_a<-t(A)%*%B
result_b<-t(B)%*%(A%*%t(A))
result_c<-(A%*%t(A))%*%t(B)
result_d<-solve((B%*%t(B))+(A%*%t(A))-100*diag(3))
print("Result of AT.B:")
print(result_a)
print("Result of BT.(A.AT):")
print(result_b)
print("Result of (A.AT).BT")
print(result_c)
print("Result of[(B.BT)+(A.AT)-100*diag(3)^(-1):")
print(result_d)